{{- define "common.cronjob.tpl" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  labels:
    a: {{ .Values.value_a }}
    b: {{ .Values.value_b }}
    c: {{ .Values.value_c }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
{{- end -}}