helm_deployment(
    name = 'actual-project-actual-task-prod',
    dependencies = ['//actual-project:actual-project'],
    sources = [
        'common/values.yaml',
        'actual-project/values.yaml',
        'actual-project/actual-task/values.yaml',
    ],
    tags = ['actual-project'],
)
